package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"time"

	"github.com/spf13/cobra"

	"github.com/IshaanNene/ScrapeGoat/internal/config"
	"github.com/IshaanNene/ScrapeGoat/internal/engine"
	"github.com/IshaanNene/ScrapeGoat/internal/fetchlog"
)

var (
	replayOutput string
	replayFormat string
	replayConfig string
	verifyJSON   bool
)

// replayCmd re-runs a recorded crawl from its log instead of from the network.
func replayCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "replay [log-dir]",
		Short: "Re-run a recorded crawl from its fetch log",
		Long: `Replay a crawl recorded with "scrapegoat crawl --record".

No sockets are opened: every response comes from the log. That makes a replay
fast, offline, and repeatable, and it is what lets a dataset be regenerated by
someone who does not have access to the sites it came from.

Seeds and configuration come from the log's manifest, so a replay reproduces the
original policy by default. Point --config at a different file to run the same
recorded responses through different crawler settings — the responses are held
fixed, so any difference in the output is attributable to the policy change.`,
		Args: cobra.ExactArgs(1),
		RunE: runReplay,
	}

	cmd.Flags().StringVarP(&replayOutput, "output", "o", "./replay-output", "output directory or file path")
	cmd.Flags().StringVarP(&replayFormat, "format", "f", "json", "output format: json, jsonl, csv")
	cmd.Flags().StringVar(&replayConfig, "config-override", "", "replay under a different config file instead of the recorded one")

	return cmd
}

func runReplay(_ *cobra.Command, args []string) error {
	logger := setupLogger()
	dir := args[0]

	manifest, err := fetchlog.ReadManifest(dir)
	if err != nil {
		return err
	}

	cfg, err := replayConfigFor(manifest)
	if err != nil {
		return err
	}
	// Whatever the recording said about output, this run writes where it was told.
	cfg.Storage.Type = replayFormat
	cfg.Storage.OutputPath = replayOutput

	// A replay exists to reproduce a run, so a scheduling-dependent record order
	// would defeat it: the records would be right and the file would still differ.
	cfg.Storage.DeterministicOrder = true

	player, err := fetchlog.NewPlayer(dir)
	if err != nil {
		return fmt.Errorf("open log: %w", err)
	}
	defer player.Close()

	if !manifest.Complete() {
		fmt.Fprintf(os.Stderr,
			"  note: this log is from a crawl that did not finish; the replay stops where it stopped\n")
	}
	if manifest.RandSeed == 0 {
		fmt.Fprintf(os.Stderr,
			"  note: the recording did not fix a random seed, so retry jitter is not reproduced exactly\n")
	}

	fmt.Fprintf(os.Stderr, "  replaying %d recorded fetches from %s\n", player.Len(), dir)

	eng := engine.New(cfg, logger)
	eng.SetFetcher("http", player)
	if err := wireCrawlPipeline(eng, cfg, logger); err != nil {
		return err
	}

	for _, seed := range manifest.Seeds {
		if err := eng.AddSeed(seed); err != nil {
			logger.Warn("seed skipped on replay", "url", seed, "reason", err)
		}
	}

	start := time.Now()
	if err := eng.Start(); err != nil {
		return fmt.Errorf("start engine: %w", err)
	}
	eng.Wait()

	stats := eng.StatsSnapshot()
	fmt.Printf("\n  Replay complete in %s\n", time.Since(start).Round(time.Millisecond))
	fmt.Printf("   Recorded:  %d fetches in the log\n", player.Len())
	fmt.Printf("   Served:    %v requests, %v failed\n", stats["requests_sent"], stats["requests_failed"])
	fmt.Printf("   Items:     %v scraped\n", stats["items_scraped"])
	fmt.Printf("   Output:    %s\n", cfg.Storage.OutputPath)

	if replayConfig != "" {
		fmt.Printf("\n   Ran under %s, not the recorded config. Differences from the original\n", replayConfig)
		fmt.Printf("   output are attributable to the policy change: the responses were identical.\n")
	}

	return nil
}

// replayConfigFor picks the configuration a replay runs under.
func replayConfigFor(m fetchlog.Manifest) (*config.Config, error) {
	if replayConfig != "" {
		cfg, err := config.Load(replayConfig)
		if err != nil {
			return nil, fmt.Errorf("load override config: %w", err)
		}
		return cfg, nil
	}

	if len(m.Config) == 0 {
		fmt.Fprintf(os.Stderr,
			"  note: the log embeds no config; replaying under defaults, which may not match the recording\n")
		return config.DefaultConfig(), nil
	}

	cfg := config.DefaultConfig()
	if err := json.Unmarshal(m.Config, cfg); err != nil {
		return nil, fmt.Errorf("parse recorded config: %w", err)
	}
	return cfg, nil
}

// verifyCmd checks a log's integrity and reports what it can reproduce.
func verifyCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "verify [log-dir]",
		Short: "Check a fetch log's integrity",
		Long: `Verify that a fetch log is intact and internally consistent.

Every stored body is re-hashed and checked against the address it is filed under,
so tampering or bit rot is caught rather than replayed. Every log entry is checked
against the store, so an entry pointing at a body that is not there is reported
rather than discovered mid-replay.

This is what makes a published dataset checkable by someone who does not trust
whoever published it.`,
		Args: cobra.ExactArgs(1),
		RunE: runVerify,
	}

	cmd.Flags().BoolVar(&verifyJSON, "json", false, "emit the report as JSON")

	return cmd
}

type verifyReport struct {
	Dir          string   `json:"dir"`
	Version      string   `json:"recorded_with,omitempty"`
	Complete     bool     `json:"crawl_complete"`
	Seeds        []string `json:"seeds,omitempty"`
	ConfigHash   string   `json:"config_hash,omitempty"`
	Entries      int      `json:"entries"`
	Successes    int      `json:"successes"`
	Failures     int      `json:"failures"`
	UniqueURLs   int      `json:"unique_urls"`
	Objects      int      `json:"objects"`
	Bytes        int64    `json:"bytes"`
	MissingBodie []string `json:"missing_bodies,omitempty"`
	StoreOK      bool     `json:"store_intact"`
	StoreError   string   `json:"store_error,omitempty"`
}

func runVerify(_ *cobra.Command, args []string) error {
	dir := args[0]
	report := verifyReport{Dir: dir}

	// The manifest is optional: a log is still verifiable without one, it just
	// cannot say what produced it.
	if m, err := fetchlog.ReadManifest(dir); err == nil {
		report.Version = m.Version
		report.Complete = m.Complete()
		report.Seeds = m.Seeds
		report.ConfigHash = m.ConfigHash
	}

	entries, err := fetchlog.ReadLog(dir)
	if err != nil {
		return err
	}
	report.Entries = len(entries)

	store, err := fetchlog.NewStore(dir)
	if err != nil {
		return err
	}

	urls := make(map[string]bool, len(entries))
	missing := make(map[string]bool)
	for _, e := range entries {
		urls[e.URL] = true
		if e.Err != "" {
			report.Failures++
			continue
		}
		report.Successes++
		if !store.Has(e.Digest) {
			// An entry whose body is absent is worse than a missing entry: replay
			// would fail partway through a run it claimed it could reproduce.
			missing[e.URL] = true
		}
	}
	report.UniqueURLs = len(urls)
	for u := range missing {
		report.MissingBodie = append(report.MissingBodie, u)
	}
	sort.Strings(report.MissingBodie)

	if st, err := store.Stat(); err == nil {
		report.Objects = st.Objects
		report.Bytes = st.Bytes
	}

	if err := store.Verify(); err != nil {
		report.StoreOK = false
		report.StoreError = err.Error()
	} else {
		report.StoreOK = true
	}

	ok := report.StoreOK && len(report.MissingBodie) == 0

	if verifyJSON {
		enc := json.NewEncoder(os.Stdout)
		enc.SetIndent("", "  ")
		if err := enc.Encode(report); err != nil {
			return err
		}
		if !ok {
			os.Exit(1)
		}
		return nil
	}

	fmt.Printf("  Fetch log: %s\n", dir)
	if report.Version != "" {
		fmt.Printf("   Recorded with:  ScrapeGoat %s\n", report.Version)
		fmt.Printf("   Crawl:          %s\n", completeness(report.Complete))
		if report.ConfigHash != "" {
			fmt.Printf("   Config hash:    %s\n", short(report.ConfigHash))
		}
		if len(report.Seeds) > 0 {
			fmt.Printf("   Seeds:          %v\n", report.Seeds)
		}
	}
	fmt.Printf("   Entries:        %d (%d ok, %d failed) across %d URLs\n",
		report.Entries, report.Successes, report.Failures, report.UniqueURLs)
	fmt.Printf("   Store:          %d objects, %d bytes\n", report.Objects, report.Bytes)

	if !report.StoreOK {
		fmt.Printf("\n  ✗ Store failed verification: %s\n", report.StoreError)
	}
	if n := len(report.MissingBodie); n > 0 {
		fmt.Printf("\n  ✗ %d entries point at bodies the store does not have:\n", n)
		for i, u := range report.MissingBodie {
			if i == 10 {
				fmt.Printf("      … and %d more\n", n-10)
				break
			}
			fmt.Printf("      %s\n", u)
		}
	}
	if ok {
		fmt.Printf("\n  ✓ Intact. Every recorded body hashes to the address it is filed under.\n")
		return nil
	}

	os.Exit(1)
	return nil
}

func completeness(done bool) string {
	if done {
		return "finished"
	}
	return "did not finish (replay stops where the crawl stopped)"
}

func short(h string) string {
	if len(h) > 12 {
		return h[:12]
	}
	return h
}
